import type { Localized } from "@/lib/i18n";

export const mockupCopy = {
  pt: {
    reviewLine1: "Gostou?",
    reviewLine2: "Toque para avaliar",
    socialLine1: "Siga-nos",
    socialLine2: "Toque para abrir",
    loyaltyLine1: "Cartão cliente",
    loyaltyLine2: "Toque para carimbar",
    loyaltyTitle: "Café da Esquina",
    loyaltyProgress: "7 de 10 carimbos",
    loyaltyReward: "Faltam 3 para o café de oferta",
    bookingTitle: "Reservar mesa",
    bookingDate: "Sábado, 14",
    bookingPeople: "2 pessoas",
    bookingConfirm: "Confirmar reserva",
    bookingReminder: "Lembrete enviado por WhatsApp",
    waitlistTitle: "Lista de espera",
    waitlistPosition: "Está em 3.º lugar",
    waitlistEta: "Cerca de 12 minutos",
    waitlistSms: "A sua mesa está pronta! Dirija-se à entrada.",
    chatTitle: "Assistente",
    chatOnline: "Online agora",
    chatUser: "Têm mesa para 4 hoje às 20h?",
    chatBot: "Temos sim! Quer que reserve já? Só preciso do seu nome.",
    chatUser2: "Sim, em nome da Ana.",
    voiceTitle: "Chamada em curso",
    voiceCaller: "+351 91• ••• •••",
    voiceTranscript: "Posso marcar um corte para quinta à tarde?",
    voiceAnswer: "Claro. Tenho às 15h ou às 17h30.",
    voiceSummary: "Resumo enviado ao responsável",
    reviewsTitle: "Nova review",
    reviewsText: "Esperámos um pouco, mas a comida compensou.",
    reviewsDraft: "Proposta de resposta",
    reviewsReply: "Obrigado pela visita e pela paciência! Estamos a reforçar a equipa ao fim de semana.",
    reviewsApprove: "Aprovar e publicar",
    flowTrigger: "Pagamento recebido",
    flowAction1: "Emitir fatura",
    flowAction2: "Enviar por e-mail",
    flowAction3: "Atualizar folha de cálculo",
    flowDone: "Concluído em segundos",
    imageSlot: "Espaço reservado para fotografia do produto",
  },
  en: {
    reviewLine1: "Enjoyed it?",
    reviewLine2: "Tap to review",
    socialLine1: "Follow us",
    socialLine2: "Tap to open",
    loyaltyLine1: "Loyalty card",
    loyaltyLine2: "Tap to collect",
    loyaltyTitle: "Corner Café",
    loyaltyProgress: "7 of 10 stamps",
    loyaltyReward: "3 more for a free coffee",
    bookingTitle: "Book a table",
    bookingDate: "Saturday 14",
    bookingPeople: "2 guests",
    bookingConfirm: "Confirm booking",
    bookingReminder: "Reminder sent on WhatsApp",
    waitlistTitle: "Waiting list",
    waitlistPosition: "You're 3rd in line",
    waitlistEta: "About 12 minutes",
    waitlistSms: "Your table is ready! Please come to the entrance.",
    chatTitle: "Assistant",
    chatOnline: "Online now",
    chatUser: "Do you have a table for 4 tonight at 8pm?",
    chatBot: "We do! Shall I book it now? I just need your name.",
    chatUser2: "Yes, under Ana.",
    voiceTitle: "Call in progress",
    voiceCaller: "+351 91• ••• •••",
    voiceTranscript: "Can I book a haircut for Thursday afternoon?",
    voiceAnswer: "Of course. I have 3pm or 5:30pm.",
    voiceSummary: "Summary sent to the manager",
    reviewsTitle: "New review",
    reviewsText: "We waited a little, but the food made up for it.",
    reviewsDraft: "Draft reply",
    reviewsReply: "Thank you for visiting and for your patience! We're adding staff at weekends.",
    reviewsApprove: "Approve and post",
    flowTrigger: "Payment received",
    flowAction1: "Issue invoice",
    flowAction2: "Email it",
    flowAction3: "Update spreadsheet",
    flowDone: "Done in seconds",
    imageSlot: "Product photo slot",
  },
} satisfies Localized<Record<string, string>>;

export type MockupCopy = (typeof mockupCopy)["pt"];
