import type { Localized } from "@/lib/i18n";

const pt = {
  product: {
    problemEyebrow: "O problema",
    solutionEyebrow: "A solução",
    howEyebrow: "Como funciona",
    howTitle: "Do primeiro contacto ao primeiro resultado",
    useCasesEyebrow: "Casos de uso",
    useCasesTitle: "Como os nossos clientes o usam",
    includesTitle: "O que está incluído",
    priceTitle: "Investimento",
    priceNote: "Recebe uma proposta fechada depois da demonstração. Sem surpresas.",
    docsTitle: "Documentação completa",
    docsBody: "Guias passo a passo para instalar, configurar e tirar o máximo partido.",
    ctaEyebrow: "Vamos a isso?",
    ctaTitle: "Veja-o a funcionar no seu negócio.",
    ctaBody: "Numa demonstração gratuita de 20 minutos mostramos tudo em direto e respondemos às suas dúvidas, sem compromisso.",
    requestInfoLead: "Ainda não é altura para uma demonstração?",
    requestInfoCta: "Peça informação por e-mail",
    packsTitle: "Packs com desconto",
    packsCount: "{count} placas",
    packsUnit: "{price} por placa",
    packsLogoOnce: "Logótipo e cores: +{price} uma só vez por pack, porque o desenho é feito uma vez para todas as placas.",
    family: { nfc: "NFC e fidelização", operations: "Reservas e filas", ai: "Inteligência artificial" },
  },
  products: {
    metaTitle: "Produtos: placas NFC, reservas e IA para negócios | Steevanz",
    metaDescription: "Placas NFC para reviews no Google, redes sociais e cardápio digital, cartão de fidelidade, reservas, lista de espera, chatbot, voz e automação com IA.",
    eyebrow: "Produtos",
    title: "Ferramentas simples para negócios que atendem pessoas.",
    lead: "Dez soluções que funcionam sozinhas ou em conjunto. Todas configuradas por nós, todas com suporte em português.",
    familyLeads: {
      nfc: "Um toque no telemóvel para reviews, seguidores, o menu e clientes fiéis.",
      operations: "Menos telefonemas, menos faltas e menos filas à porta.",
      ai: "Atendimento e tarefas repetitivas tratados por inteligência artificial, com supervisão humana.",
    },
    bundlesEyebrow: "Por setor",
    bundlesTitle: "Combinações recomendadas",
    bundlesLead: "Não sabe por onde começar? Estas são as combinações que mais fazem a diferença em cada tipo de negócio.",
  },
  sectors: {
    metaTitle: "Soluções por setor: restaurantes, salões, clínicas e lojas | Steevanz",
    metaDescription: "Placas NFC, reservas, filas e inteligência artificial adaptadas a restaurantes, cabeleireiros, clínicas e comércio local em Portugal.",
    eyebrow: "Setores",
    title: "Cada negócio tem os seus momentos certos.",
    lead: "Escolha o seu setor e veja as soluções que mais fazem a diferença no dia a dia.",
    painsEyebrow: "Os desafios",
    painsTitle: "O que ouvimos todos os dias",
    bundleEyebrow: "A solução",
    dayEyebrow: "Um dia com a Steevanz",
    dayTitle: "Como fica o seu dia",
    otherSectors: "Outros setores",
  },
};

export type PageLabels = typeof pt;

const en: PageLabels = {
  product: {
    problemEyebrow: "The problem",
    solutionEyebrow: "The solution",
    howEyebrow: "How it works",
    howTitle: "From first contact to first result",
    useCasesEyebrow: "Use cases",
    useCasesTitle: "How businesses use it",
    includesTitle: "What's included",
    priceTitle: "Investment",
    priceNote: "You get a fixed proposal after the demo. No surprises.",
    docsTitle: "Full documentation",
    docsBody: "Step-by-step guides to set up, configure and get the most out of it.",
    ctaEyebrow: "Shall we?",
    ctaTitle: "See it working for your business.",
    ctaBody: "In a free 20-minute demo we show you everything live and answer your questions, with no commitment.",
    requestInfoLead: "Not ready for a demo yet?",
    requestInfoCta: "Request info by email",
    packsTitle: "Discounted packs",
    packsCount: "{count} plates",
    packsUnit: "{price} per plate",
    packsLogoOnce: "Logo and colours: +{price} once per pack, because we design it once for every plate.",
    family: { nfc: "NFC and loyalty", operations: "Bookings and queues", ai: "Artificial intelligence" },
  },
  products: {
    metaTitle: "Products: NFC plates, bookings and AI for business | Steevanz",
    metaDescription: "NFC plates for Google reviews, social media and digital menus, loyalty cards, bookings, waiting lists, AI chat, AI voice and automation.",
    eyebrow: "Products",
    title: "Simple tools for businesses that serve people.",
    lead: "Ten solutions that work on their own or together. All set up by us, all with friendly local support.",
    familyLeads: {
      nfc: "One tap of a phone for reviews, followers, your menu and loyal customers.",
      operations: "Fewer phone calls, fewer no-shows and fewer queues at the door.",
      ai: "Customer service and repetitive tasks handled by AI, with human oversight.",
    },
    bundlesEyebrow: "By sector",
    bundlesTitle: "Recommended bundles",
    bundlesLead: "Not sure where to start? These are the combinations that make the biggest difference for each type of business.",
  },
  sectors: {
    metaTitle: "Solutions by sector: restaurants, salons, clinics, shops | Steevanz",
    metaDescription: "NFC plates, bookings, queues and artificial intelligence tailored to restaurants, hair salons, clinics and local retail in Portugal.",
    eyebrow: "Sectors",
    title: "Every business has its own right moments.",
    lead: "Choose your sector and see the solutions that make the biggest day-to-day difference.",
    painsEyebrow: "The challenges",
    painsTitle: "What we hear every day",
    bundleEyebrow: "The solution",
    dayEyebrow: "A day with Steevanz",
    dayTitle: "What your day looks like",
    otherSectors: "Other sectors",
  },
};

export const pageLabels: Localized<PageLabels> = { pt, en };
