import type { Localized } from "@/lib/i18n";

const pt = {
  skipToContent: "Saltar para o conteúdo",
  nav: {
    products: "Produtos",
    sectors: "Setores",
    docs: "Documentação",
    about: "Sobre",
    contact: "Contacto",
    bookDemo: "Agendar demonstração",
    bookDemoShort: "Agendar demo",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    allProducts: "Ver todos os produtos",
    families: { nfc: "NFC e fidelização", operations: "Reservas e filas", ai: "Inteligência artificial" },
    mainNavLabel: "Navegação principal",
  },
  theme: { toggle: "Mudar tema", light: "Tema claro", dark: "Tema escuro" },
  language: { label: "Idioma", switchTo: "Mudar para inglês", short: "EN", current: "PT" },
  footer: {
    blurb: "Placas NFC e inteligência artificial para negócios locais. Nós tratamos da tecnologia, o seu negócio trata dos clientes.",
    productsTitle: "Produtos",
    companyTitle: "Empresa",
    resourcesTitle: "Recursos",
    legalTitle: "Legal",
    contactTitle: "Fale connosco",
    rights: "Todos os direitos reservados.",
    madeIn: "Feito em Portugal, com os bons modos de sempre.",
    pricesNote: "Preços sem IVA. Valores indicativos, sujeitos a confirmação na proposta.",
  },
  common: {
    from: "desde",
    perMonth: "/mês",
    vatExcluded: "+ IVA",
    provisional: "Preço indicativo",
    learnMore: "Saber mais",
    readDocs: "Ler a documentação",
    bookDemo: "Agendar demonstração",
    requestInfo: "Pedir informação",
    whatsapp: "Falar no WhatsApp",
    whatsappMessage: "Olá! Gostava de saber mais sobre as soluções da Steevanz.",
    breadcrumbHome: "Início",
    faqTitle: "Perguntas frequentes",
    relatedProducts: "Produtos relacionados",
    backToTop: "Voltar ao topo",
    onThisPage: "Nesta página",
    previous: "Anterior",
    next: "Seguinte",
    mediaPlaceholder: "Imagem do produto",
  },
  billing: {
    "one-time": "pagamento único",
    monthly: "por mês",
    project: "por projeto",
  },
};

export type UiStrings = typeof pt;

const en: UiStrings = {
  skipToContent: "Skip to content",
  nav: {
    products: "Products",
    sectors: "Sectors",
    docs: "Docs",
    about: "About",
    contact: "Contact",
    bookDemo: "Book a demo",
    bookDemoShort: "Book a demo",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    allProducts: "See all products",
    families: { nfc: "NFC and loyalty", operations: "Bookings and queues", ai: "Artificial intelligence" },
    mainNavLabel: "Main navigation",
  },
  theme: { toggle: "Toggle theme", light: "Light theme", dark: "Dark theme" },
  language: { label: "Language", switchTo: "Switch to Portuguese", short: "PT", current: "EN" },
  footer: {
    blurb: "NFC plates and artificial intelligence for local businesses. We handle the technology, you handle your customers.",
    productsTitle: "Products",
    companyTitle: "Company",
    resourcesTitle: "Resources",
    legalTitle: "Legal",
    contactTitle: "Talk to us",
    rights: "All rights reserved.",
    madeIn: "Made in Portugal, with good old-fashioned manners.",
    pricesNote: "Prices exclude VAT. Indicative values, confirmed in your proposal.",
  },
  common: {
    from: "from",
    perMonth: "/month",
    vatExcluded: "+ VAT",
    provisional: "Indicative price",
    learnMore: "Learn more",
    readDocs: "Read the docs",
    bookDemo: "Book a demo",
    requestInfo: "Request info",
    whatsapp: "Chat on WhatsApp",
    whatsappMessage: "Hi! I'd like to know more about Steevanz solutions.",
    breadcrumbHome: "Home",
    faqTitle: "Frequently asked questions",
    relatedProducts: "Related products",
    backToTop: "Back to top",
    onThisPage: "On this page",
    previous: "Previous",
    next: "Next",
    mediaPlaceholder: "Product image",
  },
  billing: {
    "one-time": "one-off payment",
    monthly: "per month",
    project: "per project",
  },
};

export const ui: Localized<UiStrings> = { pt, en };
